name: Build

on: [push, pull_request]

jobs:

  portable:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Wait for pip release, sleep in seconds
        run: sleep 1
        shell: bash

      # only update version file once.
      - name: Update version information
        if: matrix.os == 'ubuntu-22.04'
        run: |
          echo '{ "version": '${GITHUB_REF##*/}' }'
        shell: bash

